using ICSharpCode.Decompiler.CSharp.Syntax;
using ICSharpCode.Decompiler.CSharp.Transforms;

namespace GodotMonoDecomp.Transforms;

/// <summary>
/// Restores source-level shape for methods generated by the Regex source generator.
/// </summary>
public class RestoreGeneratedRegexMethods : DepthFirstAstVisitor, IAstTransform
{
	private const string GeneratedRegexAttributeFullName = "System.Text.RegularExpressions.GeneratedRegexAttribute";
	private const string GeneratedCodeAttributeFullName = "System.CodeDom.Compiler.GeneratedCodeAttribute";
	private const string RegexGeneratorName = "System.Text.RegularExpressions.Generator";

	public void Run(AstNode rootNode, TransformContext context)
	{
		rootNode.AcceptVisitor(this);
	}

	public override void VisitMethodDeclaration(MethodDeclaration methodDeclaration)
	{
		if (!HasGeneratedRegexAttribute(methodDeclaration))
		{
			base.VisitMethodDeclaration(methodDeclaration);
			return;
		}

		bool hasRegexGeneratorGeneratedCode = Common.RemoveGeneratedCodeAttributes(methodDeclaration.Attributes, RegexGeneratorName);
		bool hasGeneratedBodyPattern = HasGeneratedRegexBodyPattern(methodDeclaration);
		if (!hasGeneratedBodyPattern && !hasRegexGeneratorGeneratedCode)
		{
			base.VisitMethodDeclaration(methodDeclaration);
			return;
		}

		methodDeclaration.Modifiers |= Modifiers.Partial;
		methodDeclaration.Body = null;
		if (methodDeclaration.Parent is TypeDeclaration containingType)
		{
			containingType.Modifiers |= Modifiers.Partial;
		}
	}

	private static bool HasGeneratedRegexAttribute(MethodDeclaration methodDeclaration)
	{
		foreach (var section in methodDeclaration.Attributes)
		{
			foreach (var attribute in section.Attributes)
			{
				if (Common.IsAttribute(attribute, GeneratedRegexAttributeFullName, "GeneratedRegex"))
				{
					return true;
				}
			}
		}

		return false;
	}

	private static bool RemoveRegexGeneratorGeneratedCodeAttributes(MethodDeclaration methodDeclaration)
	{
		return Common.RemoveGeneratedCodeAttributes(methodDeclaration.Attributes, RegexGeneratorName);
	}

	private static bool HasGeneratedRegexBodyPattern(MethodDeclaration methodDeclaration)
	{
		if (methodDeclaration.Body is not { Statements.Count: 1 })
		{
			return false;
		}

		if (methodDeclaration.Body.Statements.First() is not ReturnStatement returnStatement)
		{
			return false;
		}

		if (returnStatement.Expression is not MemberReferenceExpression memberReference)
		{
			return false;
		}

		if (!string.Equals(memberReference.MemberName, "Instance", StringComparison.Ordinal))
		{
			return false;
		}

		string targetText = memberReference.Target.ToString();
		return targetText.Contains("RegexGenerator", StringComparison.Ordinal)
			|| targetText.Contains("_003CRegexGenerator", StringComparison.Ordinal);
	}
}
